apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: octane-collector
  name: octane-collector
rules:

- apiGroups:
  - "metrics.k8s.io"
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list

- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - list
