apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: octane-collector
  name: octane-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: octane-collector
subjects:
- kind: ServiceAccount
  namespace: default
  name: octane-collector
