---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: octane-metrics-server
  namespace: "{{ .Values.namespace }}"
  labels:
    app: octane-metrics-server
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:octane-metrics-server-aggregated-reader
  labels:
    app: octane-metrics-server
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods","nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:octane-metrics-server
  labels:
    app: octane-metrics-server
rules:
  - apiGroups:
    - ""
    resources:
      - pods
      - nodes
      - nodes/stats
      - namespaces
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: octane-metrics-server:system:auth-delegator
  labels:
    app: octane-metrics-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: octane-metrics-server
    namespace: "{{ .Values.namespace }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:octane-metrics-server
  labels:
    app: octane-metrics-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:octane-metrics-server
subjects:
  - kind: ServiceAccount
    name: octane-metrics-server
    namespace: "{{ .Values.namespace }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: octane-metrics-server-auth-reader
  namespace: "{{ .Values.namespace }}"
  labels:
    app: octane-metrics-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - kind: ServiceAccount
    name: octane-metrics-server
    namespace: "{{ .Values.namespace }}"
---
apiVersion: v1
kind: Service
metadata:
  name: octane-metrics-server
  namespace: "{{ .Values.namespace }}"
  labels:
    app: octane-metrics-server
  annotations:
    {}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: https
  selector:
    app: octane-metrics-server
    release: octane-metrics-server
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: octane-metrics-server
  namespace: "{{ .Values.namespace }}"
  labels:
    app: octane-metrics-server
spec:
  selector:
    matchLabels:
      app: octane-metrics-server
      release: octane-metrics-server
  replicas: 1
  template:
    metadata:
      labels:
        app: octane-metrics-server
        release: octane-metrics-server
    spec:
      serviceAccountName: octane-metrics-server
      containers:
        - name: octane-metrics-server
          image: "k8s.gcr.io/metrics-server-amd64:v0.3.6"
          imagePullPolicy: IfNotPresent
          command:
            - /metrics-server
            - --cert-dir=/tmp
            - --logtostderr
            - --secure-port=8443
          ports:
          - containerPort: 8443
            name: https
          livenessProbe:
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
            initialDelaySeconds: 20
          resources:
            {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - all
            readOnlyRootFilesystem: true
            runAsGroup: 10001
            runAsNonRoot: true
            runAsUser: 10001
          volumeMounts:
          - name: tmp
            mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.metrics.k8s.io
  labels:
    app: octane-metrics-server
spec:
  service:
    name: octane-metrics-server
    namespace: "{{ .Values.namespace }}"
  group: metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
